# Generated by Django 6.0.5 on 2026-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='security_policies',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
