# Generated by Django 6.0.5 on 2026-05-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_syllabus_logentry_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
