# Generated by Django 6.0.5 on 2026-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendancerecord_status_classsession_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
