# Generated by Django 6.0.5 on 2026-05-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='api.projectgroup'),
        ),
    ]
