# Generated by Django 6.0.5 on 2026-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assignment_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
