# Generated by Django 6.0.5 on 2026-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_enrollment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='text_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
